sudo: required
services:
  - docker

# build a test runner container and assign it to the Dockerfile.dev within frontend
# we can't use Dockerfile as the container does not contain all the packages/ files required to run tests
before_install:
  - docker build -t joegitau/react-test -f ./frontend/Dockerfile.dev

# run the tests
script:
  - docker run joegitau/react-test npm test -- --coverage 

after_success:
  # docker image for frontend
  - docker build -t joegitau/fibonacci-frontend ./frontend

  # docker image for nginx
  - docker build  -t joegitau/fibonacci-nginx ./nginx

  # docker image for api
  - docker build -t joegitau/fibonacci-api ./api

  # docker image for worker
  - docker buiild -t joegitau/fibonacci-worker ./worker

  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # push the images to docker hub
  - docker push joegitau/fibonacci-frontend
  - docker push joegitau/fibonacci-nginx
  - docker push joegitau/fibonacci-api
  - docker push joegitau/fibonacci-worker