version: '3.8'
services:
  #Postgres image
  postgres: 
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  # redis image
  redis:
    image: 'redis:latest'
  
  # nginx build
  nginx:
    restart: always
    build:
      context: './nginx'
      dockerfile: Dockerfile.dev
    ports:
      - 3050:80
  
  # server build
  api:
    build:
      context: './api'
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    
  # frontend build
  frontend:
    build: 
      context: './frontend'
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
  
  # worker build
  worker:
    build: 
      context: './worker'
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app